name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk zip unzip
        pip install cython==0.29.36 buildozer==1.5.0
    
    - name: Accept licenses
      run: |
        mkdir -p ~/.android/licenses
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > ~/.android/licenses/android-sdk-license
    
    - name: Build APK
      run: buildozer android debug
    
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ATSC-Wallet
        path: bin/*.apk
